FROM golang:1.18-alpine AS build


WORKDIR /app
COPY . .

RUN go mod tidy

RUN go build -o /app/comment-service ./comment-service

FROM alpine:latest

WORKDIR /app

COPY --from=build /app/comment-service .

CMD ["./comment-service"]

