FROM golang:1.18-alpine AS build


WORKDIR /app
COPY . .

RUN go mod tidy

RUN go build -o /app/auth-service ./auth-service

FROM alpine:latest

WORKDIR /app

COPY --from=build /app/auth-service .

CMD ["./auth-service"]
