FROM golang:1.18-alpine AS build


WORKDIR /app
COPY . .

RUN go mod tidy
RUN go build -o /app/graphql ./graphql


FROM alpine:latest

WORKDIR  /app

COPY --from=build /app/graphql  .

CMD ["./graphql"]