apiVersion: apps/v1
kind: Deployment
metadata:
  name: HaalSamachar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: your-docker-image:latest
          ports:
            - containerPort: 8080